### ISSUE TITLE
Multi line Python source

### ISSUE THREAD

**Issue by tmeghe** [prologin/camisole#38]
Is there a work-around to test (small) multi-line Python code ? For instance, small functions (5 lines).

**Comment by Zopieux** [comment]
Just use escaped (as in *JSON escaped*) newlines in the source string:
```python
import sys

sys.stdout.write("hello world\n")
```
becomes (note the double escape for the `\n` in the string):
```json
{"source": "import sys\n\nsys.stdout.write(\"hello world\\n\")\n"}
```

Of course you could use a real JSON serializer instead of writing such strings by hand. You can use the [httpie](https://httpie.org/doc#linux) tool do ease this process, for instance:
```
$ http POST localhost:42920/run \
    lang=python tests:='{["stdin": "foo"]}' \
    source=@script.py
```

**Comment by Zopieux** [comment]
b5543d4 fixes the fact that a content-type header is required in curl(1).
